#!/bin/bash

./element_parametric.py

set -m

trap 'kill %%' EXIT

../../openpixelcontrol/bin/gl_server -l element_viz/element_parametric.json & processing-java --run --force --sketch=`pwd`/element_viz --output=`pwd`/element_viz_output

wait